# Page settings

baseURL = "/"
languageCode = "en"
title = "Curriculum Vitae"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = ""


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Muhamad Andhika Prasetya"
        tagline = "Automation Engineering Technology"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Surabaya"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+6289 563 142 1101"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:kontak@anadhika.my.id"
        text = "kontak@andhika.my.id"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "cv.andhika.my.id"
        text = "cv.andhika.my.id"




    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Network Design"
        [[params.skills.list.items]]
        details = "Server Administration"
        [[params.skills.list.items]]
        details = "Internet of Things Design"
        [[params.skills.list.items]]
        details = "Industrial Automation"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true
    
        [[params.education.list]]
        degree = "Study Abroad: Asia University Summer Program 2020"
        university = "Asia University, Taiwan"
        dates = "2020"
        [[params.education.list]]
        degree = "Network and Computer Engineering"
        university = "Vocational High School 1 Surabaya"
        dates = "2015 - 2018"
        [[params.education.list]]
        degree = "S.Tr.T (B.A.Sc) Automation Engineering Technology"
        university = "Institut Teknologi Sepuluh Nopember"
        dates = "2018 - 2022"








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "5th Place National Business Competition 2020"
        body = "University of Bangka Belitung"
        date = "2020"
        [[params.awards.list]]
        name = "Finalist at 3D Conquest"
        body = "CIMB Indonesia"
        date = "2018"
        [[params.awards.list]]
        name = "Finalist Internet of Things Competition by Telkom University"
        body = "Telkom University"
        date = "2017"
        [[params.awards.list]]
        name = "2nd Place Runner Up at Capture the Flag Competition 2017"
        body = "Narotama University"
        date = "2017"
        [[params.awards.list]]
        name = "3nd Place Runner Up at Capture the Flag Competition 2016"
        body = "Narotama University"
        date = "2016"
        [[params.awards.list]]
        name = "5th Place Runner up at Lomba Kompetensi Siswa with Internet of Things Field"
        body = "Directorate of Vocational High School Indonesia"
        date = "2017"
        [[params.awards.list]]
        name = "6th Place Runner up at Cyber Defence Competition 2015"
        body = "Surabaya City Government"
        date = "2015"







    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Indonesia"
        level = "Mother Tongue"
        [[params.languages.list]]
        name = "Java"
        level = "Mother Tongue"
        [[params.languages.list]]
        name = "English"
        level = "Active"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Internet of Things"
        [[params.interests.list]]
        name = "Industrial Automation"
        [[params.interests.list]]
        name = "Linux Community"








    [params.summary]
        enable = true
        text = "Student of the Department of Electrical Engineering Automation, ITS. Interested in technological developments, specifically IoT, Network, Server"








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Computer Network Trainer"
        dates = "January - April 2020"
        company = "Elips Computer Academy Surabaya"
        details = "Working as a trainer on Elips Computer Academy focusing on material:"
        [[params.experience.list.items]]
        details = "Basic Networking"
        [[params.experience.list.items]]
        details = "VLAN, Trunking"
        [[params.experience.list.items]]
        details = "Routing"


        [[params.experience.list]]
        title = "Network Support Engineer"
        dates = "February 2020"
        company = "Quantum HRM International"
        details = "Responsible for designing Network Storage System at PT Quantum HRM International"

        [[params.experience.list]]
        title = "Network Support Engineer"
        dates = "May 2019"
        company = "Credit Union Mandiri Jawa Timur"
        details = "Responsible as Network and System Designer at CU Mandiri Jawa Timur"




    [params.internship]
            enable = true

            [[params.internship.list]]
            title = "Internship at Directorate of Technology Development and Inforation System"
            dates = "2016"
            company = "Institut Teknologi Sepuluh Nopember"
            details = "Internship with research field on network and system engineering"





    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Industrial Internet of Things Designer"
        meta = "PT Fans Indonesia"
        tagline = "Responsible for designing IoT monitoring system for Automation System at PT Fans Indonesia"
        [[params.projects.list]]
        title = "Intelligent System Home Controlling (Internet of Things)"
        meta = "Open Source"
        tagline = "Designing Smart Home System for Telkom University IoT Competition 2017"




    [params.information]
        enable = true

        [[params.information.list]]
        title = "Speaker"
        [[params.information.list.items]]
        details = "2020 · IoT Platform: NodeRed · Konferensi Pekerja IT 2020"
        [[params.information.list.items]]
        details = "2019 · IoT Server Workshop with Blynk · APJII Jawa Timur"
        [[params.information.list.items]]
        details = "2019 · Minimizing International Internet Traffic Usage From Internet of Things Devices Using Local Server on openSUSE with Blynk · openSUSE Asia Summit 2019"
        [[params.information.list.items]]
        details = "2017 · Application of IoT in Everyday Life · Cangkrukan KLAS"

        [[params.information.list]]
        title = "License and Sertification"
        [[params.information.list.items]]
        details = "July 2020 - July 2022 · Big Data Specialist Certification - Scale Python on Cloud · Alibaba Cloud"
        [[params.information.list.items]]
        details = "Sept 2019 - Sept 2022 · Network Engineer · National Professional Certification Board (BNSP)"
        [[params.information.list.items]]
        details = "Jan 2018 - Jan 2021 · Local Area Network Engineer · National Professional Certification Board (BNSP)"

        [[params.information.list]]
        title = "Organization"
        [[params.information.list.items]]
        details = "September 2020 - Present · Chairman · Surabaya Linux User Group (KLAS)"
        [[params.information.list.items]]
        details = "Jan 2020 - Present · Coordinator · Microelectronics and Embedded System Laboratory"
        [[params.information.list.items]]
        details = "Dec 2019 - September 2020 · Training Staff · Surabaya Linux User Group (KLAS)"
        [[params.information.list.items]]
        details = "Sept 2016 - Sept 2017 · Coordinator of Research and Development Division · IT Club Vocational High School 1 Surabaya"

        [[params.information.list]]
        title = "Voluntary Experience"
        [[params.information.list.items]]
        details = "March 2020 · Judge · Robokidz Robot Olympiad 2020"
        [[params.information.list.items]]
        details = "Oct 2019 · Committe Staff · Indonesia Open Infastructure Day 2019"
        [[params.information.list.items]]
        details = "Oct 2019 · Committe Staff · International Conference on Advance Mechatronics, Intelligent Manufacture and Industrial Automation"
        [[params.information.list.items]]
        details = "Oct 2019 · Moderator Parallel Session · International Conference on Advance Mechatronics, Intelligent Manufacture and Industrial Automation"
        [[params.information.list.items]]
        details = "Sept 2019 · Judge Assistant · Indonesia Robotic Olympiad 2019"


        [params.social]
            enable = true

            [[params.social.list]]
            icon = "fab fa-github-square"
            url = "//github.com/andhikasaja/"
            title = "andhikasaja"
            [[params.social.list]]
            icon = "fab fa-linkedin"
            url = "//linkedin.com/in/andhikasaja"
            title = "andhikasaja"
            [[params.social.list]]
            icon = "fab fa-instagram"
            url = "//instagram.com/mas.andhikasaja"
            title = "@mas.andhikasaja"
            [[params.social.list]]
            icon = "fab fa-facebook"
            url = "//fb.com/andhika.prat"
            title = "andhika"
